---
- name: create Xresources file
  template:
    src="{{ X11.resource_theme | default('default') }}.j2"
    dest="{{ lookup('env', 'HOME') }}/.Xresources"
    validate="/usr/bin/env xrdb -merge %s"
