# vim: set ai et ts=2 sts=2 sw=2 syntax=ansible:

---

- name: addons | polybar | make config directory
  file:
    path="{{ lookup('env', 'HOME') }}/.config/polybar"
    recurse=yes
    state=directory

- name: addons | polybar | install launch script
  copy:
    src=polybar-launch.sh
    dest="{{ lookup('env', 'HOME') }}/.config/polybar/launch.sh"
    mode=0755
    follow=yes

- include: genconfig.yml display_item={{ item }}
  with_items: "{{ i3.addons.polybar.displays | default([]) }}"
  when: i3.addons.polybar.displays is not none
