# vim: set syntax=yaml ai ts=2 sts=2 sw=2:

---

X11:
  resource_theme: pragmata
  xft:
    dpi: 160

pulseaudio:
  device: 1

xkb:
  map_toggle: 'grp:sclk_toggle'
  layouts: 'us,ru'
  variants: ',phoenetic_winkeys'

system:
  terminal_emulator: '/sbin/termite'
  file_explorer: '/usr/bin/thunar'
  display:
    primary: eDP1

i3:
  addons:
    rofi:
      font: 'Iosevka Term Slab Light 18'
      theme: pragmata
    polybar:
      enabled: true
      displays:
        - name: eDP1
          bar_height: 50
          bar_width: 100%
        - name: HDMI3
          bar_height: 50
          bar_width: 100%
  exec:
    - cmd: "$HOME/.screenlayout/default.sh"
      no_startup_id: true
  exec_always:
    - cmd: "$HOME/.config/polybar/launch.sh"
      no_startup_id: true
  launcher: rofi -show run
  dex_launcher: rofi -show drun
  workspace_count: 10
  map_workspaces_to_primary: false
  bar:
    enabled: false
    status_command: 'polybar ~/.config/polybar/config'
    font: 'pango:Iosevka Light 12'
    padding: '8px'
