# vim: set syntax=yaml ai ts=2 sts=2 sw=2:

---

X11:
  resource_theme: pragmata
  xft:
    dpi: 96

pulseaudio:
  device: 0

xkb:
  map_toggle: 'grp:sclk_toggle'
  layouts: 'us,ru'
  variants: ',phoenetic_winkeys'

system:
  terminal_emulator: 'terminology'
  file_explorer: '/usr/bin/thunar'
  display:
    primary: eDP1

rofi:
  font: 'Iosevka Term Slab Light 18'
  theme: pragmata

i3:
  launcher: rofi -show run
  dex_launcher: rofi -show drun
  workspace_count: 10
  bar:
    status_command: 'python3 ~/.config/i3pystatus/config.py'
    font: 'pango:Iosevka Light 12'
    padding: '8px'
