# vim: set syntax=yaml ai ts=2 sts=2 sw=2:

---

X11:
  resource_theme: pragmata
  xft:
    dpi: 160

pulseaudio:
  device: 0

xkb:
  map_toggle: 'grp:sclk_toggle'
  layouts: 'us,ru'
  variants: ',phoenetic_winkeys'

system:
  terminal_emulator: 'terminology'
  file_explorer: '/usr/bin/thunar'
  display:
    primary: eDP1

rofi:
  font: 'Iosevka Term Slab Light 18'
  theme: pragmata

i3:
  exec:
    - cmd: "$HOME/.screenlayout/default.sh"
      no_startup_id: true
  exec_always:
    - cmd: "$HOME/.config/polybar/launch.sh"
      no_startup_id: true
  launcher: rofi -show run
  dex_launcher: rofi -show drun
  workspace_count: 10
  bar:
    enabled: false
    status_command: 'polybar ~/.config/polybar/config'
    font: 'pango:Iosevka Light 12'
    padding: '8px'
