---

- block:
  - name: arch | reconcile packages
    pacman:
      name="{{ item.name }}"
      state="{{ item.state | default('latest') }}"
      force="{{ item.force | default('no') }}"
    become: true
    when: "not item.aur | default(False)"
    with_items: "{{ packages }}"

  - name: arch-aur | install packages
    aur:
      name="{{ item.name }}"
      user="{{ lookup('env', 'USER') }}"
      dir="{{ archlinux.aur.package_dir | default('/tmp') }}"
    when: "item.aur | default(False)"
    with_items: "{{ packages }}"
